version: 2.0

executors:
  minimal-elixir:
    docker:
      - image: circleci/elixir:1.11.2
        environment:
          DOCKER_ENV: test
          MIX_ENV: test

jobs:
  build:
    executor: minimal-elixir
    working_directory: ~/circleci-demo-elixir
    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix do deps.get, compile --warnings-as-errors

  lint:
    executor: minimal-elixir
    steps:
      - run: mix credo --strict
      - run: mix dialyzer --format short

  test:
    executor: minimal-elixir
    steps:
      - test: mix do deps.get, compile --warnings-as-errors, mix test
