version: 2.0

executors:
  my-executor:
    docker:
      - image: circleci/elixir:1.11.2

jobs:
  build:
    executor: my-executor
    working_directory: ~/circleci-demo-elixir
    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix do deps.get, compile --warnings-as-errors

  lint:
    executor: my-executor
    steps:
      - run: mix credo --strict
      - run: mix dialyzer --format short

  test:
    executor: my-executor
    steps:
      - test: mix do deps.get, compile --warnings-as-errors, mix test
